apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: free-ip-space
      protocol: layer2
      addresses:
      - 192.168.124.230-192.168.124.250
